# Generated by Django 4.2.1 on 2023-07-09 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inscription', '0007_personne_date_inscription'),
        ('salaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaire',
            name='Comptable_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inscription.personne'),
        ),
    ]
