# Generated by Django 4.2.1 on 2023-07-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0002_salaire_comptable_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaire',
            name='Comptable_id',
            field=models.IntegerField(null=True),
        ),
    ]
