# Generated by Django 4.2.1 on 2023-07-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inscription', '0004_alter_personne_valide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='valide',
        ),
    ]
