# Generated by Django 4.2.1 on 2023-07-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscription', '0006_personne_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='date_inscription',
            field=models.DateTimeField(null=True),
        ),
    ]
