# Generated by Django 4.2.1 on 2023-06-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutement', '0002_candidature'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='documents',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
