# Generated by Django 4.2.1 on 2023-06-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutement', '0003_offre_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='date_soumission',
            field=models.DateTimeField(null=True),
        ),
    ]
