# Generated by Django 4.2.1 on 2023-06-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutement', '0006_offre_date_offre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='recruteur',
        ),
    ]
