# Generated by Django 4.2.1 on 2023-06-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutement', '0007_remove_offre_recruteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='valide',
            field=models.BooleanField(null=True),
        ),
    ]
