# Generated by Django 4.2.1 on 2023-06-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutement', '0008_offre_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='nom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='prenom',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
