# Generated by Django 4.2.1 on 2023-06-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutement', '0010_candidature_objet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
