# Generated by Django 4.2.1 on 2023-06-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutement', '0011_alter_candidature_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='valide',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
