# Generated by Django 4.2.1 on 2023-06-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutement', '0012_candidature_valide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='demande_document',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='demande_dossier',
        ),
    ]
