# Generated by Django 4.2.1 on 2023-07-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inscription', '0002_candidat'),
        ('Recrutement', '0013_remove_offre_demande_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifcandidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateTimeField(null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inscription.candidat')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recrutement.offre')),
            ],
        ),
    ]
