# Generated by Django 4.2.1 on 2023-07-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutement', '0014_notifcandidature'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifcandidature',
            name='Marque',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
