# Generated by Django 4.2.1 on 2023-07-09 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inscription', '0007_personne_date_inscription'),
        ('Recrutement', '0015_notifcandidature_marque'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='Responsable_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inscription.personne'),
        ),
    ]
