# Generated by Django 4.2.1 on 2023-07-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutement', '0016_offre_responsable_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='Responsable_id',
            field=models.IntegerField(null=True),
        ),
    ]
