# Generated by Django 4.2.1 on 2023-07-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutement', '0017_alter_offre_responsable_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='Donttouch',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
