# Generated by Django 4.2.1 on 2023-07-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutement', '0018_candidature_donttouch'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='Donttouch',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
