# Generated by Django 4.2.1 on 2023-07-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employeur', '0002_messagerie_date_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerie',
            name='Marque',
            field=models.BooleanField(null=True),
        ),
    ]
