# Generated by Django 4.2.1 on 2023-07-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employeur', '0003_messagerie_marque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagerie',
            name='Marque',
        ),
    ]
