# Generated by Django 4.2.1 on 2023-07-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employeur', '0004_remove_messagerie_marque'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerie',
            name='Marque',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
